.PHONY: all test clean docs
.PHONY: $(projects_release)
.PHONY: $(projects_clean_release)
.PHONY: $(tests_release)
.PHONY: $(tests_clean_release)
.PHONY: $(projects_debug)
.PHONY: $(projects_clean_debug)
.PHONY: $(tests_debug)
.PHONY: $(tests_clean_debug)
.PHONY: $(projects_profile)
.PHONY: $(projects_clean_profile)
.PHONY: $(tests_profile)
.PHONY: $(tests_clean_profile)
.PHONY: $(projects_install) $(projects_doc)

RELEASE_PROJECTS=terrat_ui_js_cache terrat_session kqueue_bindings_gen terrat_tag_query_lexer abb_fut_js terrat_vcs_service terrat_vcs_service_nyi hcl_lexer lua_pattern abb_js_xmlhttprequest terrat_access_token_caps terrat_job_type terrat_vcs_event_evaluator terrat_user ttm_kv terrat_vcs_service_github ttm cohttp_abb_curl terrat_ee terrat_github abb_bounded_suspendable_executor abb_curl_easy oth_abb terrat_ui_js_service_vcs terrat_code_indexer jwk terrat_tier terrat json_of_yaml abb_thread_pool localforage terrat_ui_files terrat_change_match3 kqueue terrat_files_gitlab abb_scheduler_luv ttm_client uritmpl abb_intf terrat_vcs_event_evaluator2 gitlabc ttm_secrets kv_store_intf abb_tcp_server pgsql_codec terrat_vcs_github_comment terrat_task terrat_ui_js_service_github terrat_migrations_ex terrat_vcs_service_github_oss simple_diff abb_bounded_executor abb_scheduler_select terrat_vcs_provider2_nyi dns_cli json_schema terrat_access_control2 furi brtl_mw_log git_config abb_scheduler_kqueue abb_channel jsonu terrat_code_idx brtl_pagination snabela_cli hcl_ast lua_pattern_sed abb terrat_tag_query pgsql_io abb_curl_cli kqueue_bindings terrat_pull_request terrat_telemetry openapi abb_curl_easy_cli terrat_work_manifest3 terrat_ui_css openapi_conv snabela opentofu_mods json_of_yaml-rs abb_cache githubc2_cli abb_dns abb_test service_worker abb_keyed_concurrent_executor terrat_vcs_api_github abb_tls terrat_vcs_comment abb_scheduler_nyi jsonschema_check abb_js_fetch brtl_mw_session ouuid terrat_ui_sw terrat_oss abb_service_local json_schema_hooks_cli abb_curl terrat_cli terrat_commit_check brtl_permissions static_meta_pkg terrat_vcs_provider2 cohttp_abb abb_domain_pool terrat_vcs_api_nyi terrat_tag_set terrat_vcs_provider2_gitlab terrat_github_webhooks_decoder terrat_tag_query_parser_value opentofu_mods_cli brtl terrat_files terrat_base_repo_config_v1 terrat_ui_js_service revops terrat_config openapi_cli jsonschema-rs brtl_static lua_pattern_cli terrat_job_context_param brtl_js terrat_storage brtl_js2 terrat_ui_site hcl_parser abb_js terrat_data terrat_repo_config hcl_ast_cli openapic_abb data_mig terrat_github_webhooks pgsql_test_client githubc2_abb otls_bindings terrat_vcs_gitlab_comment terrat_vcs_access_token prmths gitlab_webhooks_decoder terrat_vcs_stacks abb_time terrat_vcs_service_gitlab terrat_vcs_api_gitlab brtl_hello_world iris githubc2 tabler_icons tailwindcss terrat_change tls_server abbs_tls abb_flow abb_channel_queue json_schema_conv terrat_vcs_event_evaluator2_targets pds_excise terrat_vcs_service_gitlab_ee gitlab_webhooks yaml_of_json terrat_plan_diff minijinja-rs terrat_scope yaml_of_json-rs terrat_metrics terrat_vcs_api abb_future_combinators otls_bindings_gen jwk_fetch terrat_tag_query_parser abb_process terrat_vcs_gitlab_comment_templates terrat_ui_js_service_gitlab abb_fut abbs abb_happy_eyeballs minijinja terrat_vcs_service_gitlab_oss terrat_kv_store str_template terrat_ui_js terrat_vcs_service_github_ee terrat_comment hljs tls_client terrat_gate abb_service_serializer jwt buildsys otls sln terrat_sql_of_tag_query terrat_tag_query_ast abb_io markdown_it terrat_dirspace brtl_ep terrat_job_context brtl_js_nav_bar hcl_parser_value terrat_user_caps oth terrat_vcs_kv_store pgsql_pagination terrat_vcs_github_comment_templates pgsql_pool buildsys_intf terrat_vcs_provider2_github terrat_api showdown_js 
RELEASE_TESTS=terrat_base_repo_config_v1 terrat_repo_config terrat_github_webhooks abb_time githubc2 abb_flow yaml_of_json abb_future_combinators abb_fut minijinja str_template jwt buildsys otls terrat_sql_of_tag_query abb_channel_queue_fut abb_io revops_ordering oth lua_pattern abb_bounded_suspendable_executor terrat json_of_yaml abb_thread_pool kqueue abb_scheduler_luv uritmpl gitlabc ttm_secrets pgsql_codec revops_undo simple_diff abb_scheduler_select furi git_config abb_scheduler_kqueue jsonu hcl_ast pgsql_io snabela abb_cache abb_keyed_concurrent_executor terrat_vcs_comment revops_temp_file jsonschema_check abb_service_local cohttp_abb 
DEBUG_PROJECTS=terrat_ui_js_cache terrat_session kqueue_bindings_gen terrat_tag_query_lexer abb_fut_js terrat_vcs_service terrat_vcs_service_nyi hcl_lexer lua_pattern abb_js_xmlhttprequest terrat_access_token_caps terrat_job_type terrat_vcs_event_evaluator terrat_user ttm_kv terrat_vcs_service_github ttm cohttp_abb_curl terrat_ee terrat_github abb_bounded_suspendable_executor abb_curl_easy oth_abb terrat_ui_js_service_vcs terrat_code_indexer jwk terrat_tier terrat json_of_yaml abb_thread_pool localforage terrat_ui_files terrat_change_match3 kqueue terrat_files_gitlab abb_scheduler_luv ttm_client uritmpl abb_intf terrat_vcs_event_evaluator2 gitlabc ttm_secrets kv_store_intf abb_tcp_server pgsql_codec terrat_vcs_github_comment terrat_task terrat_ui_js_service_github terrat_migrations_ex terrat_vcs_service_github_oss simple_diff abb_bounded_executor abb_scheduler_select terrat_vcs_provider2_nyi dns_cli json_schema terrat_access_control2 furi brtl_mw_log git_config abb_scheduler_kqueue abb_channel jsonu terrat_code_idx brtl_pagination snabela_cli hcl_ast lua_pattern_sed abb terrat_tag_query pgsql_io abb_curl_cli kqueue_bindings terrat_pull_request terrat_telemetry openapi abb_curl_easy_cli terrat_work_manifest3 terrat_ui_css openapi_conv snabela opentofu_mods json_of_yaml-rs abb_cache githubc2_cli abb_dns abb_test service_worker abb_keyed_concurrent_executor terrat_vcs_api_github abb_tls terrat_vcs_comment abb_scheduler_nyi jsonschema_check abb_js_fetch brtl_mw_session ouuid terrat_ui_sw terrat_oss abb_service_local json_schema_hooks_cli abb_curl terrat_cli terrat_commit_check brtl_permissions static_meta_pkg terrat_vcs_provider2 cohttp_abb abb_domain_pool terrat_vcs_api_nyi terrat_tag_set terrat_vcs_provider2_gitlab terrat_github_webhooks_decoder terrat_tag_query_parser_value opentofu_mods_cli brtl terrat_files terrat_base_repo_config_v1 terrat_ui_js_service revops terrat_config openapi_cli jsonschema-rs brtl_static lua_pattern_cli terrat_job_context_param brtl_js terrat_storage brtl_js2 terrat_ui_site hcl_parser abb_js terrat_data terrat_repo_config hcl_ast_cli openapic_abb data_mig terrat_github_webhooks pgsql_test_client githubc2_abb otls_bindings terrat_vcs_gitlab_comment terrat_vcs_access_token prmths gitlab_webhooks_decoder terrat_vcs_stacks abb_time terrat_vcs_service_gitlab terrat_vcs_api_gitlab brtl_hello_world iris githubc2 tabler_icons tailwindcss terrat_change tls_server abbs_tls abb_flow abb_channel_queue json_schema_conv terrat_vcs_event_evaluator2_targets pds_excise terrat_vcs_service_gitlab_ee gitlab_webhooks yaml_of_json terrat_plan_diff minijinja-rs terrat_scope yaml_of_json-rs terrat_metrics terrat_vcs_api abb_future_combinators otls_bindings_gen jwk_fetch terrat_tag_query_parser abb_process terrat_vcs_gitlab_comment_templates terrat_ui_js_service_gitlab abb_fut abbs abb_happy_eyeballs minijinja terrat_vcs_service_gitlab_oss terrat_kv_store str_template terrat_ui_js terrat_vcs_service_github_ee terrat_comment hljs tls_client terrat_gate abb_service_serializer jwt buildsys otls sln terrat_sql_of_tag_query terrat_tag_query_ast abb_io markdown_it terrat_dirspace brtl_ep terrat_job_context brtl_js_nav_bar hcl_parser_value terrat_user_caps oth terrat_vcs_kv_store pgsql_pagination terrat_vcs_github_comment_templates pgsql_pool buildsys_intf terrat_vcs_provider2_github terrat_api showdown_js 
DEBUG_TESTS=terrat_base_repo_config_v1 terrat_repo_config terrat_github_webhooks abb_time githubc2 abb_flow yaml_of_json abb_future_combinators abb_fut minijinja str_template jwt buildsys otls terrat_sql_of_tag_query abb_channel_queue_fut abb_io revops_ordering oth lua_pattern abb_bounded_suspendable_executor terrat json_of_yaml abb_thread_pool kqueue abb_scheduler_luv uritmpl gitlabc ttm_secrets pgsql_codec revops_undo simple_diff abb_scheduler_select furi git_config abb_scheduler_kqueue jsonu hcl_ast pgsql_io snabela abb_cache abb_keyed_concurrent_executor terrat_vcs_comment revops_temp_file jsonschema_check abb_service_local cohttp_abb 
PROFILE_PROJECTS=terrat_ui_js_cache terrat_session kqueue_bindings_gen terrat_tag_query_lexer abb_fut_js terrat_vcs_service terrat_vcs_service_nyi hcl_lexer lua_pattern abb_js_xmlhttprequest terrat_access_token_caps terrat_job_type terrat_vcs_event_evaluator terrat_user ttm_kv terrat_vcs_service_github ttm cohttp_abb_curl terrat_ee terrat_github abb_bounded_suspendable_executor abb_curl_easy oth_abb terrat_ui_js_service_vcs terrat_code_indexer jwk terrat_tier terrat json_of_yaml abb_thread_pool localforage terrat_ui_files terrat_change_match3 kqueue terrat_files_gitlab abb_scheduler_luv ttm_client uritmpl abb_intf terrat_vcs_event_evaluator2 gitlabc ttm_secrets kv_store_intf abb_tcp_server pgsql_codec terrat_vcs_github_comment terrat_task terrat_ui_js_service_github terrat_migrations_ex terrat_vcs_service_github_oss simple_diff abb_bounded_executor abb_scheduler_select terrat_vcs_provider2_nyi dns_cli json_schema terrat_access_control2 furi brtl_mw_log git_config abb_scheduler_kqueue abb_channel jsonu terrat_code_idx brtl_pagination snabela_cli hcl_ast lua_pattern_sed abb terrat_tag_query pgsql_io abb_curl_cli kqueue_bindings terrat_pull_request terrat_telemetry openapi abb_curl_easy_cli terrat_work_manifest3 terrat_ui_css openapi_conv snabela opentofu_mods json_of_yaml-rs abb_cache githubc2_cli abb_dns abb_test service_worker abb_keyed_concurrent_executor terrat_vcs_api_github abb_tls terrat_vcs_comment abb_scheduler_nyi jsonschema_check abb_js_fetch brtl_mw_session ouuid terrat_ui_sw terrat_oss abb_service_local json_schema_hooks_cli abb_curl terrat_cli terrat_commit_check brtl_permissions static_meta_pkg terrat_vcs_provider2 cohttp_abb abb_domain_pool terrat_vcs_api_nyi terrat_tag_set terrat_vcs_provider2_gitlab terrat_github_webhooks_decoder terrat_tag_query_parser_value opentofu_mods_cli brtl terrat_files terrat_base_repo_config_v1 terrat_ui_js_service revops terrat_config openapi_cli jsonschema-rs brtl_static lua_pattern_cli terrat_job_context_param brtl_js terrat_storage brtl_js2 terrat_ui_site hcl_parser abb_js terrat_data terrat_repo_config hcl_ast_cli openapic_abb data_mig terrat_github_webhooks pgsql_test_client githubc2_abb otls_bindings terrat_vcs_gitlab_comment terrat_vcs_access_token prmths gitlab_webhooks_decoder terrat_vcs_stacks abb_time terrat_vcs_service_gitlab terrat_vcs_api_gitlab brtl_hello_world iris githubc2 tabler_icons tailwindcss terrat_change tls_server abbs_tls abb_flow abb_channel_queue json_schema_conv terrat_vcs_event_evaluator2_targets pds_excise terrat_vcs_service_gitlab_ee gitlab_webhooks yaml_of_json terrat_plan_diff minijinja-rs terrat_scope yaml_of_json-rs terrat_metrics terrat_vcs_api abb_future_combinators otls_bindings_gen jwk_fetch terrat_tag_query_parser abb_process terrat_vcs_gitlab_comment_templates terrat_ui_js_service_gitlab abb_fut abbs abb_happy_eyeballs minijinja terrat_vcs_service_gitlab_oss terrat_kv_store str_template terrat_ui_js terrat_vcs_service_github_ee terrat_comment hljs tls_client terrat_gate abb_service_serializer jwt buildsys otls sln terrat_sql_of_tag_query terrat_tag_query_ast abb_io markdown_it terrat_dirspace brtl_ep terrat_job_context brtl_js_nav_bar hcl_parser_value terrat_user_caps oth terrat_vcs_kv_store pgsql_pagination terrat_vcs_github_comment_templates pgsql_pool buildsys_intf terrat_vcs_provider2_github terrat_api showdown_js 
PROFILE_TESTS=terrat_base_repo_config_v1 terrat_repo_config terrat_github_webhooks abb_time githubc2 abb_flow yaml_of_json abb_future_combinators abb_fut minijinja str_template jwt buildsys otls terrat_sql_of_tag_query abb_channel_queue_fut abb_io revops_ordering oth lua_pattern abb_bounded_suspendable_executor terrat json_of_yaml abb_thread_pool kqueue abb_scheduler_luv uritmpl gitlabc ttm_secrets pgsql_codec revops_undo simple_diff abb_scheduler_select furi git_config abb_scheduler_kqueue jsonu hcl_ast pgsql_io snabela abb_cache abb_keyed_concurrent_executor terrat_vcs_comment revops_temp_file jsonschema_check abb_service_local cohttp_abb 

projects_release = $(RELEASE_PROJECTS:%=release_%)
projects_clean_release = $(RELEASE_PROJECTS:%=clean-release_%)
projects_debug = $(DEBUG_PROJECTS:%=debug_%)
projects_clean_debug = $(DEBUG_PROJECTS:%=clean-debug_%)
projects_profile = $(PROFILE_PROJECTS:%=profile_%)
projects_clean_profile = $(PROFILE_PROJECTS:%=clean-profile_%)

projects_install = $(RELEASE_PROJECTS:%=install_%)
projects_docs = $(RELEASE_PROJECTS:%=docs_%)
projects_remove = $(RELEASE_PROJECTS:%=remove_%)

tests_release = $(RELEASE_TESTS:%=test-release_%)
tests_clean_release = $(RELEASE_TESTS:%=test-clean-release_%)
tests_debug = $(DEBUG_TESTS:%=test-debug_%)
tests_clean_debug = $(DEBUG_TESTS:%=test-clean-debug_%)
tests_profile = $(PROFILE_TESTS:%=test-profile_%)
tests_clean_profile = $(PROFILE_TESTS:%=test-clean-profile_%)

all: release

release: $(projects_release)

release_terrat_ui_js_cache: 

release_terrat_session: release_brtl release_brtl_mw_session release_terrat_storage release_terrat_user 

release_kqueue_bindings_gen: release_kqueue_bindings 

release_terrat_tag_query_lexer: release_terrat_tag_query_parser 

release_abb_fut_js: release_abb_fut 

release_terrat_vcs_service: release_brtl release_terrat_config release_terrat_storage release_terrat_user release_terrat_vcs_api release_terrat_vcs_event_evaluator2 release_terrat_vcs_provider2 

release_terrat_vcs_service_nyi: 

release_hcl_lexer: release_hcl_parser 

release_lua_pattern: 

release_abb_js_xmlhttprequest: release_abb_fut_js 

release_terrat_access_token_caps: release_json_schema release_openapi 

release_terrat_job_type: release_json_schema 

release_terrat_vcs_event_evaluator: release_abb_flow release_ouuid release_prmths release_sln release_str_template release_terrat_base_repo_config_v1 release_terrat_comment release_terrat_storage release_terrat_user release_terrat_vcs_provider2 

release_terrat_user: release_abb release_jwt release_pgsql_io release_terrat_access_token_caps release_terrat_storage release_terrat_user_caps 

release_ttm_kv: release_abb release_abbs release_kv_store_intf release_terrat_access_token_caps release_terrat_user_caps release_ttm_client 

release_terrat_vcs_service_github: release_brtl_permissions release_minijinja release_pgsql_io release_pgsql_pagination release_pgsql_pool release_terrat_api release_terrat_code_idx release_terrat_files release_terrat_github release_terrat_github_webhooks release_terrat_github_webhooks_decoder release_terrat_metrics release_terrat_plan_diff release_terrat_scope release_terrat_session release_terrat_sql_of_tag_query release_terrat_task release_terrat_telemetry release_terrat_user release_terrat_vcs_api_github release_terrat_vcs_event_evaluator release_terrat_vcs_event_evaluator2 release_terrat_vcs_github_comment release_terrat_vcs_kv_store release_terrat_vcs_provider2 release_terrat_vcs_provider2_github release_terrat_vcs_service release_terrat_vcs_stacks 

release_ttm: release_abb release_static_meta_pkg release_ttm_kv release_ttm_secrets 

release_cohttp_abb_curl: release_abb_intf release_abb_io release_abb_scheduler_select release_cohttp_abb release_otls 

release_terrat_ee: release_terrat_cli release_terrat_vcs_service_github_ee release_terrat_vcs_service_gitlab_ee 

release_terrat_github: release_abb release_abbs release_githubc2 release_githubc2_abb release_jwt release_openapi release_prmths release_terrat_config 

release_abb_bounded_suspendable_executor: release_abb_intf release_abb_service_local release_abb_time 

release_abb_curl_easy: release_abb_intf 

release_oth_abb: release_abb_future_combinators release_abb_intf release_oth 

release_terrat_ui_js_service_vcs: release_abb_js release_brtl_js2 release_terrat_api release_terrat_tier 

release_terrat_code_indexer: release_opentofu_mods release_sln 

release_jwk: 

release_terrat_tier: 

release_terrat: release_abb release_abb_cache release_abb_curl release_abb_flow release_abb_happy_eyeballs release_abb_keyed_concurrent_executor release_abb_process release_abbs release_abbs_tls release_brtl release_brtl_ep release_brtl_mw_log release_brtl_mw_session release_brtl_pagination release_brtl_permissions release_brtl_static release_data_mig release_git_config release_githubc2 release_githubc2_abb release_jsonu release_jwt release_lua_pattern release_ouuid release_pgsql_pool release_prmths release_terrat_api release_terrat_base_repo_config_v1 release_terrat_change release_terrat_change_match3 release_terrat_code_idx release_terrat_comment release_terrat_commit_check release_terrat_config release_terrat_data release_terrat_dirspace release_terrat_files release_terrat_metrics release_terrat_migrations_ex release_terrat_plan_diff release_terrat_pull_request release_terrat_repo_config release_terrat_session release_terrat_storage release_terrat_tag_query release_terrat_tag_query_ast release_terrat_tag_query_lexer release_terrat_tag_query_parser release_terrat_tag_set release_terrat_telemetry release_terrat_user release_terrat_vcs_service release_terrat_work_manifest3 

release_json_of_yaml: release_json_of_yaml-rs 

release_abb_thread_pool: 

release_localforage: release_abb_fut_js 

release_terrat_ui_files: release_terrat_ui_css release_terrat_ui_js release_terrat_ui_site 

release_terrat_change_match3: release_sln release_terrat_base_repo_config_v1 release_terrat_change release_terrat_dirspace release_terrat_tag_query 

release_kqueue: release_kqueue_bindings release_kqueue_bindings_gen 

release_terrat_files_gitlab: 

release_abb_scheduler_luv: release_abb_domain_pool release_abb_fut release_abb_intf 

release_ttm_client: release_abb release_openapic_abb release_terrat_api 

release_uritmpl: 

release_abb_intf: 

release_terrat_vcs_event_evaluator2: release_abb release_abb_bounded_suspendable_executor release_abbs release_buildsys release_ouuid release_prmths release_terrat_base_repo_config_v1 release_terrat_comment release_terrat_kv_store release_terrat_storage release_terrat_vcs_event_evaluator release_terrat_vcs_event_evaluator2_targets release_terrat_vcs_provider2 

release_gitlabc: release_json_schema release_openapi 

release_ttm_secrets: 

release_kv_store_intf: 

release_abb_tcp_server: release_abb_channel release_abb_channel_queue release_abb_intf 

release_pgsql_codec: 

release_terrat_vcs_github_comment: release_abb_future_combinators release_minijinja release_pgsql_io release_pgsql_pagination release_pgsql_pool release_terrat_comment release_terrat_files release_terrat_github release_terrat_plan_diff release_terrat_scope release_terrat_vcs_api_github release_terrat_vcs_comment release_terrat_vcs_github_comment_templates release_terrat_vcs_provider2 release_terrat_work_manifest3 

release_terrat_task: release_abb release_abbs release_pgsql_io release_terrat_storage 

release_terrat_ui_js_service_github: release_abb_js release_abb_js_fetch release_brtl_js2 release_tabler_icons release_terrat_api release_terrat_ui_js_service 

release_terrat_migrations_ex: release_pgsql_io release_pgsql_pool release_terrat_config release_terrat_storage 

release_terrat_vcs_service_github_oss: release_terrat_vcs_api_github release_terrat_vcs_provider2 release_terrat_vcs_service release_terrat_vcs_service_github 

release_simple_diff: 

release_abb_bounded_executor: release_abb_intf release_abb_service_local 

release_abb_scheduler_select: release_abb_fut release_abb_intf release_abb_thread_pool 

release_terrat_vcs_provider2_nyi: release_pgsql_io release_terrat_vcs_api_nyi release_terrat_vcs_provider2 

release_dns_cli: release_abb release_abb_dns release_abbs 

release_json_schema: release_sln release_uritmpl 

release_terrat_access_control2: release_abb release_abbs release_terrat_base_repo_config_v1 release_terrat_change release_terrat_change_match3 release_terrat_config 

release_furi: 

release_brtl_mw_log: release_abb_intf release_brtl 

release_git_config: release_sln 

release_abb_scheduler_kqueue: release_abb_domain_pool release_abb_fut release_abb_intf release_kqueue 

release_abb_channel: release_abb_future_combinators release_abb_intf 

release_jsonu: release_json_of_yaml release_yaml_of_json 

release_terrat_code_idx: release_terrat_api 

release_brtl_pagination: 

release_snabela_cli: release_snabela 

release_hcl_ast: release_hcl_lexer release_hcl_parser release_hcl_parser_value 

release_lua_pattern_sed: release_lua_pattern 

release_abb: release_abb_intf release_abb_scheduler_luv 

release_terrat_tag_query: release_terrat_dirspace release_terrat_tag_query_ast release_terrat_tag_set 

release_pgsql_io: release_abb release_abb_intf release_abbs release_abbs_tls release_ouuid release_pgsql_codec 

release_abb_curl_cli: release_abb_curl release_abb_scheduler_luv 

release_kqueue_bindings: 

release_terrat_pull_request: 

release_terrat_telemetry: release_abb release_abb_curl release_abbs release_terrat_config release_terrat_work_manifest3 

release_openapi: release_json_schema 

release_abb_curl_easy_cli: release_abb_curl_easy release_abb_scheduler_luv 

release_terrat_work_manifest3: release_terrat_base_repo_config_v1 release_terrat_change release_terrat_tag_query 

release_terrat_ui_css: release_tailwindcss release_terrat_ui_js release_terrat_ui_site 

release_openapi_conv: release_json_schema_conv release_sln 

release_snabela: release_sln 

release_opentofu_mods: release_hcl_ast 

release_json_of_yaml-rs: 

release_abb_cache: release_abb release_abb_future_combinators release_abb_intf release_abb_io 

release_githubc2_cli: release_abb release_abbs release_githubc2 release_githubc2_abb release_otls 

release_abb_dns: release_abb_future_combinators release_abb_intf release_abb_io 

release_abb_test: release_abb_future_combinators release_abb_intf release_oth release_oth_abb 

release_service_worker: release_abb_fut_js release_abb_js 

release_abb_keyed_concurrent_executor: release_abb_future_combinators release_abb_intf release_abb_service_local 

release_terrat_vcs_api_github: release_githubc2 release_githubc2_abb release_prmths release_terrat_github release_terrat_metrics release_terrat_pull_request release_terrat_vcs_api 

release_abb_tls: release_abb_future_combinators release_abb_intf release_abb_io release_otls 

release_terrat_vcs_comment: release_abbs release_terrat_data release_terrat_dirspace 

release_abb_scheduler_nyi: release_abb_fut release_abb_intf 

release_jsonschema_check: release_jsonschema-rs 

release_abb_js_fetch: release_abb_fut_js 

release_brtl_mw_session: release_abb_intf release_brtl 

release_ouuid: 

release_terrat_ui_sw: release_abb_fut_js release_brtl_js release_service_worker release_terrat_ui_js_cache 

release_terrat_oss: release_terrat_cli release_terrat_vcs_service_github_oss release_terrat_vcs_service_gitlab_oss 

release_abb_service_local: release_abb_channel release_abb_channel_queue 

release_json_schema_hooks_cli: release_json_schema_conv 

release_abb_curl: release_abb_channel release_abb_future_combinators release_abb_intf release_abb_service_local release_sln 

release_terrat_cli: release_terrat release_terrat_github 

release_terrat_commit_check: 

release_brtl_permissions: release_abbs release_brtl release_brtl_ep 

release_static_meta_pkg: 

release_terrat_vcs_provider2: release_abb release_jsonu release_pgsql_io release_str_template release_terrat_access_control2 release_terrat_api release_terrat_base_repo_config_v1 release_terrat_change release_terrat_commit_check release_terrat_config release_terrat_gate release_terrat_job_context release_terrat_pull_request release_terrat_tier release_terrat_vcs_api release_terrat_vcs_stacks release_terrat_work_manifest3 

release_cohttp_abb: release_abb_channel release_abb_channel_queue release_abb_future_combinators release_abb_happy_eyeballs release_abb_intf release_abb_io release_abb_tls release_oth release_oth_abb 

release_abb_domain_pool: 

release_terrat_vcs_api_nyi: release_terrat_change release_terrat_pull_request 

release_terrat_tag_set: release_sln 

release_terrat_vcs_provider2_gitlab: release_terrat_job_context_param release_terrat_job_type release_terrat_vcs_api_gitlab release_terrat_vcs_comment release_terrat_vcs_provider2 

release_terrat_github_webhooks_decoder: release_json_schema release_terrat_github_webhooks 

release_terrat_tag_query_parser_value: 

release_opentofu_mods_cli: release_opentofu_mods 

release_brtl: release_abb_intf release_abbs release_cohttp_abb release_ouuid release_snabela 

release_terrat_files: 

release_terrat_base_repo_config_v1: release_jsonschema_check release_lua_pattern release_sln release_terrat_data release_terrat_repo_config release_terrat_tag_query 

release_terrat_ui_js_service: release_abb_fut_js release_abb_js release_brtl_js2 release_hljs release_tabler_icons release_terrat_api release_terrat_dirspace release_terrat_plan_diff release_terrat_ui_js_service_vcs 

release_revops: 

release_terrat_config: 

release_openapi_cli: release_openapi_conv 

release_jsonschema-rs: 

release_brtl_static: release_abbs release_brtl 

release_lua_pattern_cli: release_lua_pattern 

release_terrat_job_context_param: release_json_schema 

release_brtl_js: release_abb_js release_furi release_ouuid 

release_terrat_storage: release_pgsql_pool release_prmths release_terrat_config 

release_brtl_js2: release_abb_js release_furi 

release_terrat_ui_site: release_terrat_ui_js 

release_hcl_parser: release_hcl_parser_value 

release_abb_js: release_abb_fut_js release_abb_future_combinators 

release_terrat_data: release_sln release_terrat_dirspace 

release_terrat_repo_config: release_json_schema 

release_hcl_ast_cli: release_hcl_ast 

release_openapic_abb: release_abb release_abb_curl release_abbs release_json_schema release_openapi 

release_data_mig: release_abbs 

release_terrat_github_webhooks: release_json_schema 

release_pgsql_test_client: release_abb release_abbs release_oth release_oth_abb release_pgsql_io 

release_githubc2_abb: release_abb release_abb_curl release_abbs release_json_schema release_openapi 

release_otls_bindings: 

release_terrat_vcs_gitlab_comment: release_abb_future_combinators release_minijinja release_pgsql_io release_pgsql_pagination release_pgsql_pool release_terrat_comment release_terrat_files_gitlab release_terrat_plan_diff release_terrat_scope release_terrat_vcs_api_gitlab release_terrat_vcs_comment release_terrat_vcs_gitlab_comment_templates release_terrat_vcs_provider2 release_terrat_work_manifest3 

release_terrat_vcs_access_token: release_abb release_brtl release_brtl_ep release_terrat_api release_terrat_session release_terrat_user release_terrat_vcs_provider2 

release_prmths: release_abb release_abbs 

release_gitlab_webhooks_decoder: release_gitlab_webhooks 

release_terrat_vcs_stacks: release_brtl release_brtl_ep release_terrat_api release_terrat_change_match3 release_terrat_session release_terrat_storage release_terrat_user release_terrat_vcs_api 

release_abb_time: 

release_terrat_vcs_service_gitlab: release_brtl_permissions release_gitlab_webhooks release_gitlab_webhooks_decoder release_minijinja release_pgsql_pagination release_terrat_code_idx release_terrat_files_gitlab release_terrat_metrics release_terrat_plan_diff release_terrat_session release_terrat_sql_of_tag_query release_terrat_telemetry release_terrat_vcs_access_token release_terrat_vcs_api_gitlab release_terrat_vcs_event_evaluator release_terrat_vcs_event_evaluator2 release_terrat_vcs_gitlab_comment release_terrat_vcs_kv_store release_terrat_vcs_provider2 release_terrat_vcs_provider2_gitlab release_terrat_vcs_service release_terrat_vcs_stacks 

release_terrat_vcs_api_gitlab: release_gitlabc release_openapic_abb release_prmths release_terrat_files_gitlab release_terrat_vcs_api 

release_brtl_hello_world: release_abb release_brtl release_brtl_mw_log 

release_iris: 

release_githubc2: release_json_schema release_openapi 

release_tabler_icons: release_brtl_js2 

release_tailwindcss: 

release_terrat_change: release_terrat_base_repo_config_v1 release_terrat_data release_terrat_dirspace 

release_tls_server: release_otls 

release_abbs_tls: release_abb release_abb_tls 

release_abb_flow: release_abb_future_combinators release_abb_intf 

release_abb_channel_queue: release_abb_channel release_abb_future_combinators release_abb_intf 

release_json_schema_conv: release_sln 

release_terrat_vcs_event_evaluator2_targets: release_terrat_base_repo_config_v1 release_terrat_change release_terrat_comment release_terrat_dirspace release_terrat_vcs_provider2 

release_pds_excise: 

release_terrat_vcs_service_gitlab_ee: release_terrat_vcs_access_token release_terrat_vcs_provider2 release_terrat_vcs_service release_terrat_vcs_service_gitlab 

release_gitlab_webhooks: release_json_schema 

release_yaml_of_json: release_yaml_of_json-rs 

release_terrat_plan_diff: release_lua_pattern 

release_minijinja-rs: 

release_terrat_scope: release_terrat_api release_terrat_data release_terrat_dirspace 

release_yaml_of_json-rs: 

release_terrat_metrics: release_prmths 

release_terrat_vcs_api: release_abb release_pgsql_io release_terrat_change release_terrat_commit_check release_terrat_config release_terrat_pull_request 

release_abb_future_combinators: release_abb_intf 

release_otls_bindings_gen: release_otls_bindings 

release_jwk_fetch: release_abb release_abbs release_cohttp_abb release_jwk 

release_terrat_tag_query_parser: release_terrat_tag_query_parser_value 

release_abb_process: release_abb_future_combinators release_abb_intf 

release_terrat_vcs_gitlab_comment_templates: release_brtl release_terrat_files_gitlab release_terrat_plan_diff 

release_terrat_ui_js_service_gitlab: release_abb_js release_abb_js_fetch release_brtl_js2 release_tabler_icons release_terrat_api release_terrat_ui_js_service 

release_abb_fut: release_abb_intf 

release_abbs: release_abb release_abb_cache release_abb_channel release_abb_channel_queue release_abb_future_combinators release_abb_happy_eyeballs release_abb_io release_abb_service_local release_abb_service_serializer release_abb_tcp_server release_abb_time 

release_abb_happy_eyeballs: release_abb_future_combinators release_abb_intf 

release_minijinja: release_minijinja-rs 

release_terrat_vcs_service_gitlab_oss: release_terrat_vcs_provider2 release_terrat_vcs_service release_terrat_vcs_service_gitlab 

release_terrat_kv_store: release_abb release_kv_store_intf release_pgsql_io release_terrat_user 

release_str_template: release_lua_pattern 

release_terrat_ui_js: release_abb_fut_js release_abb_js release_abb_js_fetch release_brtl_js2 release_hljs release_tabler_icons release_terrat_api release_terrat_data release_terrat_dirspace release_terrat_plan_diff release_terrat_ui_js_service release_terrat_ui_js_service_github release_terrat_ui_js_service_gitlab 

release_terrat_vcs_service_github_ee: release_sln release_terrat_vcs_access_token release_terrat_vcs_provider2 release_terrat_vcs_service release_terrat_vcs_service_github 

release_terrat_comment: release_terrat_tag_query 

release_hljs: release_brtl_js2 

release_tls_client: release_otls 

release_terrat_gate: release_terrat_api release_terrat_base_repo_config_v1 

release_abb_service_serializer: release_abb_channel release_abb_service_local 

release_jwt: release_sln 

release_buildsys: release_buildsys_intf 

release_otls: release_otls_bindings release_otls_bindings_gen 

release_sln: 

release_terrat_sql_of_tag_query: release_terrat_tag_query_parser_value 

release_terrat_tag_query_ast: release_terrat_tag_query_lexer release_terrat_tag_query_parser release_terrat_tag_query_parser_value 

release_abb_io: release_abb_future_combinators release_abb_intf 

release_markdown_it: 

release_terrat_dirspace: 

release_brtl_ep: release_abbs release_brtl 

release_terrat_job_context: release_terrat_api release_terrat_tag_query 

release_brtl_js_nav_bar: release_abb_js release_brtl_js 

release_hcl_parser_value: 

release_terrat_user_caps: release_terrat_access_token_caps 

release_oth: release_revops 

release_terrat_vcs_kv_store: release_brtl release_brtl_ep release_terrat_kv_store release_terrat_session release_terrat_storage release_terrat_user release_terrat_vcs_provider2 

release_pgsql_pagination: release_abb release_abbs release_pgsql_io 

release_terrat_vcs_github_comment_templates: release_brtl release_terrat_files release_terrat_plan_diff 

release_pgsql_pool: release_abb release_abbs release_pgsql_io 

release_buildsys_intf: 

release_terrat_vcs_provider2_github: release_terrat_job_context_param release_terrat_job_type release_terrat_vcs_api_github release_terrat_vcs_comment release_terrat_vcs_provider2 

release_terrat_api: release_json_schema release_openapi 

release_showdown_js: 

test-release: $(tests_release)

test-release_terrat_base_repo_config_v1: release_oth release_terrat_base_repo_config_v1 release_terrat_repo_config 

test-release_terrat_repo_config: release_oth release_terrat_repo_config 

test-release_terrat_github_webhooks: release_oth release_terrat_github_webhooks 

test-release_abb_time: release_abb_time release_oth 

test-release_githubc2: release_githubc2 release_oth 

test-release_abb_flow: release_abb_flow release_abb_scheduler_select release_oth_abb 

test-release_yaml_of_json: release_oth release_yaml_of_json 

test-release_abb_future_combinators: release_abb_fut release_abb_future_combinators release_abb_intf release_oth 

test-release_abb_fut: release_abb_fut release_abb_intf release_oth 

test-release_minijinja: release_minijinja release_oth 

test-release_str_template: release_oth release_sln release_str_template 

test-release_jwt: release_jwt release_oth 

test-release_buildsys: release_abb_bounded_suspendable_executor release_abb_fut release_buildsys release_oth release_oth_abb 

test-release_otls: release_oth release_otls 

test-release_terrat_sql_of_tag_query: release_oth release_terrat_sql_of_tag_query release_terrat_tag_query_ast 

test-release_abb_channel_queue_fut: release_abb_channel release_abb_channel_queue release_abb_fut release_oth 

test-release_abb_io: release_abb_io release_abb_scheduler_select release_oth_abb 

test-release_revops_ordering: release_revops 

test-release_oth: release_oth 

test-release_lua_pattern: release_lua_pattern release_oth 

test-release_abb_bounded_suspendable_executor: release_abb_bounded_suspendable_executor release_abb_fut release_abb_intf release_oth 

test-release_terrat: release_oth release_terrat 

test-release_json_of_yaml: release_json_of_yaml release_oth 

test-release_abb_thread_pool: release_abb_thread_pool release_oth 

test-release_kqueue: release_kqueue release_oth 

test-release_abb_scheduler_luv: release_abb_intf release_abb_scheduler_luv release_abb_test 

test-release_uritmpl: release_oth release_uritmpl 

test-release_gitlabc: release_gitlabc release_oth 

test-release_ttm_secrets: release_oth release_ttm_secrets 

test-release_pgsql_codec: release_oth release_pgsql_codec 

test-release_revops_undo: release_revops 

test-release_simple_diff: release_oth release_simple_diff 

test-release_abb_scheduler_select: release_abb_fut release_abb_intf release_abb_scheduler_select release_abb_test 

test-release_furi: release_furi release_oth 

test-release_git_config: release_git_config release_oth 

test-release_abb_scheduler_kqueue: release_abb_intf release_abb_scheduler_kqueue release_abb_test 

test-release_jsonu: release_jsonu release_oth 

test-release_hcl_ast: release_hcl_ast release_oth 

test-release_pgsql_io: release_oth release_pgsql_io 

test-release_snabela: release_oth release_snabela 

test-release_abb_cache: release_abb_cache release_abb_scheduler_select release_oth_abb 

test-release_abb_keyed_concurrent_executor: release_abb_fut release_abb_intf release_abb_keyed_concurrent_executor release_oth 

test-release_terrat_vcs_comment: release_oth release_oth_abb release_terrat_vcs_comment 

test-release_revops_temp_file: release_revops 

test-release_jsonschema_check: release_jsonschema_check release_oth 

test-release_abb_service_local: release_abb_channel release_abb_fut release_abb_service_local release_oth 

test-release_cohttp_abb: release_abb_scheduler_select release_cohttp_abb release_oth release_oth_abb 

debug: $(projects_debug)

debug_terrat_ui_js_cache: 

debug_terrat_session: debug_brtl debug_brtl_mw_session debug_terrat_storage debug_terrat_user 

debug_kqueue_bindings_gen: debug_kqueue_bindings 

debug_terrat_tag_query_lexer: debug_terrat_tag_query_parser 

debug_abb_fut_js: debug_abb_fut 

debug_terrat_vcs_service: debug_brtl debug_terrat_config debug_terrat_storage debug_terrat_user debug_terrat_vcs_api debug_terrat_vcs_event_evaluator2 debug_terrat_vcs_provider2 

debug_terrat_vcs_service_nyi: 

debug_hcl_lexer: debug_hcl_parser 

debug_lua_pattern: 

debug_abb_js_xmlhttprequest: debug_abb_fut_js 

debug_terrat_access_token_caps: debug_json_schema debug_openapi 

debug_terrat_job_type: debug_json_schema 

debug_terrat_vcs_event_evaluator: debug_abb_flow debug_ouuid debug_prmths debug_sln debug_str_template debug_terrat_base_repo_config_v1 debug_terrat_comment debug_terrat_storage debug_terrat_user debug_terrat_vcs_provider2 

debug_terrat_user: debug_abb debug_jwt debug_pgsql_io debug_terrat_access_token_caps debug_terrat_storage debug_terrat_user_caps 

debug_ttm_kv: debug_abb debug_abbs debug_kv_store_intf debug_terrat_access_token_caps debug_terrat_user_caps debug_ttm_client 

debug_terrat_vcs_service_github: debug_brtl_permissions debug_minijinja debug_pgsql_io debug_pgsql_pagination debug_pgsql_pool debug_terrat_api debug_terrat_code_idx debug_terrat_files debug_terrat_github debug_terrat_github_webhooks debug_terrat_github_webhooks_decoder debug_terrat_metrics debug_terrat_plan_diff debug_terrat_scope debug_terrat_session debug_terrat_sql_of_tag_query debug_terrat_task debug_terrat_telemetry debug_terrat_user debug_terrat_vcs_api_github debug_terrat_vcs_event_evaluator debug_terrat_vcs_event_evaluator2 debug_terrat_vcs_github_comment debug_terrat_vcs_kv_store debug_terrat_vcs_provider2 debug_terrat_vcs_provider2_github debug_terrat_vcs_service debug_terrat_vcs_stacks 

debug_ttm: debug_abb debug_static_meta_pkg debug_ttm_kv debug_ttm_secrets 

debug_cohttp_abb_curl: debug_abb_intf debug_abb_io debug_abb_scheduler_select debug_cohttp_abb debug_otls 

debug_terrat_ee: debug_terrat_cli debug_terrat_vcs_service_github_ee debug_terrat_vcs_service_gitlab_ee 

debug_terrat_github: debug_abb debug_abbs debug_githubc2 debug_githubc2_abb debug_jwt debug_openapi debug_prmths debug_terrat_config 

debug_abb_bounded_suspendable_executor: debug_abb_intf debug_abb_service_local debug_abb_time 

debug_abb_curl_easy: debug_abb_intf 

debug_oth_abb: debug_abb_future_combinators debug_abb_intf debug_oth 

debug_terrat_ui_js_service_vcs: debug_abb_js debug_brtl_js2 debug_terrat_api debug_terrat_tier 

debug_terrat_code_indexer: debug_opentofu_mods debug_sln 

debug_jwk: 

debug_terrat_tier: 

debug_terrat: debug_abb debug_abb_cache debug_abb_curl debug_abb_flow debug_abb_happy_eyeballs debug_abb_keyed_concurrent_executor debug_abb_process debug_abbs debug_abbs_tls debug_brtl debug_brtl_ep debug_brtl_mw_log debug_brtl_mw_session debug_brtl_pagination debug_brtl_permissions debug_brtl_static debug_data_mig debug_git_config debug_githubc2 debug_githubc2_abb debug_jsonu debug_jwt debug_lua_pattern debug_ouuid debug_pgsql_pool debug_prmths debug_terrat_api debug_terrat_base_repo_config_v1 debug_terrat_change debug_terrat_change_match3 debug_terrat_code_idx debug_terrat_comment debug_terrat_commit_check debug_terrat_config debug_terrat_data debug_terrat_dirspace debug_terrat_files debug_terrat_metrics debug_terrat_migrations_ex debug_terrat_plan_diff debug_terrat_pull_request debug_terrat_repo_config debug_terrat_session debug_terrat_storage debug_terrat_tag_query debug_terrat_tag_query_ast debug_terrat_tag_query_lexer debug_terrat_tag_query_parser debug_terrat_tag_set debug_terrat_telemetry debug_terrat_user debug_terrat_vcs_service debug_terrat_work_manifest3 

debug_json_of_yaml: debug_json_of_yaml-rs 

debug_abb_thread_pool: 

debug_localforage: debug_abb_fut_js 

debug_terrat_ui_files: debug_terrat_ui_css debug_terrat_ui_js debug_terrat_ui_site 

debug_terrat_change_match3: debug_sln debug_terrat_base_repo_config_v1 debug_terrat_change debug_terrat_dirspace debug_terrat_tag_query 

debug_kqueue: debug_kqueue_bindings debug_kqueue_bindings_gen 

debug_terrat_files_gitlab: 

debug_abb_scheduler_luv: debug_abb_domain_pool debug_abb_fut debug_abb_intf 

debug_ttm_client: debug_abb debug_openapic_abb debug_terrat_api 

debug_uritmpl: 

debug_abb_intf: 

debug_terrat_vcs_event_evaluator2: debug_abb debug_abb_bounded_suspendable_executor debug_abbs debug_buildsys debug_ouuid debug_prmths debug_terrat_base_repo_config_v1 debug_terrat_comment debug_terrat_kv_store debug_terrat_storage debug_terrat_vcs_event_evaluator debug_terrat_vcs_event_evaluator2_targets debug_terrat_vcs_provider2 

debug_gitlabc: debug_json_schema debug_openapi 

debug_ttm_secrets: 

debug_kv_store_intf: 

debug_abb_tcp_server: debug_abb_channel debug_abb_channel_queue debug_abb_intf 

debug_pgsql_codec: 

debug_terrat_vcs_github_comment: debug_abb_future_combinators debug_minijinja debug_pgsql_io debug_pgsql_pagination debug_pgsql_pool debug_terrat_comment debug_terrat_files debug_terrat_github debug_terrat_plan_diff debug_terrat_scope debug_terrat_vcs_api_github debug_terrat_vcs_comment debug_terrat_vcs_github_comment_templates debug_terrat_vcs_provider2 debug_terrat_work_manifest3 

debug_terrat_task: debug_abb debug_abbs debug_pgsql_io debug_terrat_storage 

debug_terrat_ui_js_service_github: debug_abb_js debug_abb_js_fetch debug_brtl_js2 debug_tabler_icons debug_terrat_api debug_terrat_ui_js_service 

debug_terrat_migrations_ex: debug_pgsql_io debug_pgsql_pool debug_terrat_config debug_terrat_storage 

debug_terrat_vcs_service_github_oss: debug_terrat_vcs_api_github debug_terrat_vcs_provider2 debug_terrat_vcs_service debug_terrat_vcs_service_github 

debug_simple_diff: 

debug_abb_bounded_executor: debug_abb_intf debug_abb_service_local 

debug_abb_scheduler_select: debug_abb_fut debug_abb_intf debug_abb_thread_pool 

debug_terrat_vcs_provider2_nyi: debug_pgsql_io debug_terrat_vcs_api_nyi debug_terrat_vcs_provider2 

debug_dns_cli: debug_abb debug_abb_dns debug_abbs 

debug_json_schema: debug_sln debug_uritmpl 

debug_terrat_access_control2: debug_abb debug_abbs debug_terrat_base_repo_config_v1 debug_terrat_change debug_terrat_change_match3 debug_terrat_config 

debug_furi: 

debug_brtl_mw_log: debug_abb_intf debug_brtl 

debug_git_config: debug_sln 

debug_abb_scheduler_kqueue: debug_abb_domain_pool debug_abb_fut debug_abb_intf debug_kqueue 

debug_abb_channel: debug_abb_future_combinators debug_abb_intf 

debug_jsonu: debug_json_of_yaml debug_yaml_of_json 

debug_terrat_code_idx: debug_terrat_api 

debug_brtl_pagination: 

debug_snabela_cli: debug_snabela 

debug_hcl_ast: debug_hcl_lexer debug_hcl_parser debug_hcl_parser_value 

debug_lua_pattern_sed: debug_lua_pattern 

debug_abb: debug_abb_intf debug_abb_scheduler_luv 

debug_terrat_tag_query: debug_terrat_dirspace debug_terrat_tag_query_ast debug_terrat_tag_set 

debug_pgsql_io: debug_abb debug_abb_intf debug_abbs debug_abbs_tls debug_ouuid debug_pgsql_codec 

debug_abb_curl_cli: debug_abb_curl debug_abb_scheduler_luv 

debug_kqueue_bindings: 

debug_terrat_pull_request: 

debug_terrat_telemetry: debug_abb debug_abb_curl debug_abbs debug_terrat_config debug_terrat_work_manifest3 

debug_openapi: debug_json_schema 

debug_abb_curl_easy_cli: debug_abb_curl_easy debug_abb_scheduler_luv 

debug_terrat_work_manifest3: debug_terrat_base_repo_config_v1 debug_terrat_change debug_terrat_tag_query 

debug_terrat_ui_css: debug_tailwindcss debug_terrat_ui_js debug_terrat_ui_site 

debug_openapi_conv: debug_json_schema_conv debug_sln 

debug_snabela: debug_sln 

debug_opentofu_mods: debug_hcl_ast 

debug_json_of_yaml-rs: 

debug_abb_cache: debug_abb debug_abb_future_combinators debug_abb_intf debug_abb_io 

debug_githubc2_cli: debug_abb debug_abbs debug_githubc2 debug_githubc2_abb debug_otls 

debug_abb_dns: debug_abb_future_combinators debug_abb_intf debug_abb_io 

debug_abb_test: debug_abb_future_combinators debug_abb_intf debug_oth debug_oth_abb 

debug_service_worker: debug_abb_fut_js debug_abb_js 

debug_abb_keyed_concurrent_executor: debug_abb_future_combinators debug_abb_intf debug_abb_service_local 

debug_terrat_vcs_api_github: debug_githubc2 debug_githubc2_abb debug_prmths debug_terrat_github debug_terrat_metrics debug_terrat_pull_request debug_terrat_vcs_api 

debug_abb_tls: debug_abb_future_combinators debug_abb_intf debug_abb_io debug_otls 

debug_terrat_vcs_comment: debug_abbs debug_terrat_data debug_terrat_dirspace 

debug_abb_scheduler_nyi: debug_abb_fut debug_abb_intf 

debug_jsonschema_check: debug_jsonschema-rs 

debug_abb_js_fetch: debug_abb_fut_js 

debug_brtl_mw_session: debug_abb_intf debug_brtl 

debug_ouuid: 

debug_terrat_ui_sw: debug_abb_fut_js debug_brtl_js debug_service_worker debug_terrat_ui_js_cache 

debug_terrat_oss: debug_terrat_cli debug_terrat_vcs_service_github_oss debug_terrat_vcs_service_gitlab_oss 

debug_abb_service_local: debug_abb_channel debug_abb_channel_queue 

debug_json_schema_hooks_cli: debug_json_schema_conv 

debug_abb_curl: debug_abb_channel debug_abb_future_combinators debug_abb_intf debug_abb_service_local debug_sln 

debug_terrat_cli: debug_terrat debug_terrat_github 

debug_terrat_commit_check: 

debug_brtl_permissions: debug_abbs debug_brtl debug_brtl_ep 

debug_static_meta_pkg: 

debug_terrat_vcs_provider2: debug_abb debug_jsonu debug_pgsql_io debug_str_template debug_terrat_access_control2 debug_terrat_api debug_terrat_base_repo_config_v1 debug_terrat_change debug_terrat_commit_check debug_terrat_config debug_terrat_gate debug_terrat_job_context debug_terrat_pull_request debug_terrat_tier debug_terrat_vcs_api debug_terrat_vcs_stacks debug_terrat_work_manifest3 

debug_cohttp_abb: debug_abb_channel debug_abb_channel_queue debug_abb_future_combinators debug_abb_happy_eyeballs debug_abb_intf debug_abb_io debug_abb_tls debug_oth debug_oth_abb 

debug_abb_domain_pool: 

debug_terrat_vcs_api_nyi: debug_terrat_change debug_terrat_pull_request 

debug_terrat_tag_set: debug_sln 

debug_terrat_vcs_provider2_gitlab: debug_terrat_job_context_param debug_terrat_job_type debug_terrat_vcs_api_gitlab debug_terrat_vcs_comment debug_terrat_vcs_provider2 

debug_terrat_github_webhooks_decoder: debug_json_schema debug_terrat_github_webhooks 

debug_terrat_tag_query_parser_value: 

debug_opentofu_mods_cli: debug_opentofu_mods 

debug_brtl: debug_abb_intf debug_abbs debug_cohttp_abb debug_ouuid debug_snabela 

debug_terrat_files: 

debug_terrat_base_repo_config_v1: debug_jsonschema_check debug_lua_pattern debug_sln debug_terrat_data debug_terrat_repo_config debug_terrat_tag_query 

debug_terrat_ui_js_service: debug_abb_fut_js debug_abb_js debug_brtl_js2 debug_hljs debug_tabler_icons debug_terrat_api debug_terrat_dirspace debug_terrat_plan_diff debug_terrat_ui_js_service_vcs 

debug_revops: 

debug_terrat_config: 

debug_openapi_cli: debug_openapi_conv 

debug_jsonschema-rs: 

debug_brtl_static: debug_abbs debug_brtl 

debug_lua_pattern_cli: debug_lua_pattern 

debug_terrat_job_context_param: debug_json_schema 

debug_brtl_js: debug_abb_js debug_furi debug_ouuid 

debug_terrat_storage: debug_pgsql_pool debug_prmths debug_terrat_config 

debug_brtl_js2: debug_abb_js debug_furi 

debug_terrat_ui_site: debug_terrat_ui_js 

debug_hcl_parser: debug_hcl_parser_value 

debug_abb_js: debug_abb_fut_js debug_abb_future_combinators 

debug_terrat_data: debug_sln debug_terrat_dirspace 

debug_terrat_repo_config: debug_json_schema 

debug_hcl_ast_cli: debug_hcl_ast 

debug_openapic_abb: debug_abb debug_abb_curl debug_abbs debug_json_schema debug_openapi 

debug_data_mig: debug_abbs 

debug_terrat_github_webhooks: debug_json_schema 

debug_pgsql_test_client: debug_abb debug_abbs debug_oth debug_oth_abb debug_pgsql_io 

debug_githubc2_abb: debug_abb debug_abb_curl debug_abbs debug_json_schema debug_openapi 

debug_otls_bindings: 

debug_terrat_vcs_gitlab_comment: debug_abb_future_combinators debug_minijinja debug_pgsql_io debug_pgsql_pagination debug_pgsql_pool debug_terrat_comment debug_terrat_files_gitlab debug_terrat_plan_diff debug_terrat_scope debug_terrat_vcs_api_gitlab debug_terrat_vcs_comment debug_terrat_vcs_gitlab_comment_templates debug_terrat_vcs_provider2 debug_terrat_work_manifest3 

debug_terrat_vcs_access_token: debug_abb debug_brtl debug_brtl_ep debug_terrat_api debug_terrat_session debug_terrat_user debug_terrat_vcs_provider2 

debug_prmths: debug_abb debug_abbs 

debug_gitlab_webhooks_decoder: debug_gitlab_webhooks 

debug_terrat_vcs_stacks: debug_brtl debug_brtl_ep debug_terrat_api debug_terrat_change_match3 debug_terrat_session debug_terrat_storage debug_terrat_user debug_terrat_vcs_api 

debug_abb_time: 

debug_terrat_vcs_service_gitlab: debug_brtl_permissions debug_gitlab_webhooks debug_gitlab_webhooks_decoder debug_minijinja debug_pgsql_pagination debug_terrat_code_idx debug_terrat_files_gitlab debug_terrat_metrics debug_terrat_plan_diff debug_terrat_session debug_terrat_sql_of_tag_query debug_terrat_telemetry debug_terrat_vcs_access_token debug_terrat_vcs_api_gitlab debug_terrat_vcs_event_evaluator debug_terrat_vcs_event_evaluator2 debug_terrat_vcs_gitlab_comment debug_terrat_vcs_kv_store debug_terrat_vcs_provider2 debug_terrat_vcs_provider2_gitlab debug_terrat_vcs_service debug_terrat_vcs_stacks 

debug_terrat_vcs_api_gitlab: debug_gitlabc debug_openapic_abb debug_prmths debug_terrat_files_gitlab debug_terrat_vcs_api 

debug_brtl_hello_world: debug_abb debug_brtl debug_brtl_mw_log 

debug_iris: 

debug_githubc2: debug_json_schema debug_openapi 

debug_tabler_icons: debug_brtl_js2 

debug_tailwindcss: 

debug_terrat_change: debug_terrat_base_repo_config_v1 debug_terrat_data debug_terrat_dirspace 

debug_tls_server: debug_otls 

debug_abbs_tls: debug_abb debug_abb_tls 

debug_abb_flow: debug_abb_future_combinators debug_abb_intf 

debug_abb_channel_queue: debug_abb_channel debug_abb_future_combinators debug_abb_intf 

debug_json_schema_conv: debug_sln 

debug_terrat_vcs_event_evaluator2_targets: debug_terrat_base_repo_config_v1 debug_terrat_change debug_terrat_comment debug_terrat_dirspace debug_terrat_vcs_provider2 

debug_pds_excise: 

debug_terrat_vcs_service_gitlab_ee: debug_terrat_vcs_access_token debug_terrat_vcs_provider2 debug_terrat_vcs_service debug_terrat_vcs_service_gitlab 

debug_gitlab_webhooks: debug_json_schema 

debug_yaml_of_json: debug_yaml_of_json-rs 

debug_terrat_plan_diff: debug_lua_pattern 

debug_minijinja-rs: 

debug_terrat_scope: debug_terrat_api debug_terrat_data debug_terrat_dirspace 

debug_yaml_of_json-rs: 

debug_terrat_metrics: debug_prmths 

debug_terrat_vcs_api: debug_abb debug_pgsql_io debug_terrat_change debug_terrat_commit_check debug_terrat_config debug_terrat_pull_request 

debug_abb_future_combinators: debug_abb_intf 

debug_otls_bindings_gen: debug_otls_bindings 

debug_jwk_fetch: debug_abb debug_abbs debug_cohttp_abb debug_jwk 

debug_terrat_tag_query_parser: debug_terrat_tag_query_parser_value 

debug_abb_process: debug_abb_future_combinators debug_abb_intf 

debug_terrat_vcs_gitlab_comment_templates: debug_brtl debug_terrat_files_gitlab debug_terrat_plan_diff 

debug_terrat_ui_js_service_gitlab: debug_abb_js debug_abb_js_fetch debug_brtl_js2 debug_tabler_icons debug_terrat_api debug_terrat_ui_js_service 

debug_abb_fut: debug_abb_intf 

debug_abbs: debug_abb debug_abb_cache debug_abb_channel debug_abb_channel_queue debug_abb_future_combinators debug_abb_happy_eyeballs debug_abb_io debug_abb_service_local debug_abb_service_serializer debug_abb_tcp_server debug_abb_time 

debug_abb_happy_eyeballs: debug_abb_future_combinators debug_abb_intf 

debug_minijinja: debug_minijinja-rs 

debug_terrat_vcs_service_gitlab_oss: debug_terrat_vcs_provider2 debug_terrat_vcs_service debug_terrat_vcs_service_gitlab 

debug_terrat_kv_store: debug_abb debug_kv_store_intf debug_pgsql_io debug_terrat_user 

debug_str_template: debug_lua_pattern 

debug_terrat_ui_js: debug_abb_fut_js debug_abb_js debug_abb_js_fetch debug_brtl_js2 debug_hljs debug_tabler_icons debug_terrat_api debug_terrat_data debug_terrat_dirspace debug_terrat_plan_diff debug_terrat_ui_js_service debug_terrat_ui_js_service_github debug_terrat_ui_js_service_gitlab 

debug_terrat_vcs_service_github_ee: debug_sln debug_terrat_vcs_access_token debug_terrat_vcs_provider2 debug_terrat_vcs_service debug_terrat_vcs_service_github 

debug_terrat_comment: debug_terrat_tag_query 

debug_hljs: debug_brtl_js2 

debug_tls_client: debug_otls 

debug_terrat_gate: debug_terrat_api debug_terrat_base_repo_config_v1 

debug_abb_service_serializer: debug_abb_channel debug_abb_service_local 

debug_jwt: debug_sln 

debug_buildsys: debug_buildsys_intf 

debug_otls: debug_otls_bindings debug_otls_bindings_gen 

debug_sln: 

debug_terrat_sql_of_tag_query: debug_terrat_tag_query_parser_value 

debug_terrat_tag_query_ast: debug_terrat_tag_query_lexer debug_terrat_tag_query_parser debug_terrat_tag_query_parser_value 

debug_abb_io: debug_abb_future_combinators debug_abb_intf 

debug_markdown_it: 

debug_terrat_dirspace: 

debug_brtl_ep: debug_abbs debug_brtl 

debug_terrat_job_context: debug_terrat_api debug_terrat_tag_query 

debug_brtl_js_nav_bar: debug_abb_js debug_brtl_js 

debug_hcl_parser_value: 

debug_terrat_user_caps: debug_terrat_access_token_caps 

debug_oth: debug_revops 

debug_terrat_vcs_kv_store: debug_brtl debug_brtl_ep debug_terrat_kv_store debug_terrat_session debug_terrat_storage debug_terrat_user debug_terrat_vcs_provider2 

debug_pgsql_pagination: debug_abb debug_abbs debug_pgsql_io 

debug_terrat_vcs_github_comment_templates: debug_brtl debug_terrat_files debug_terrat_plan_diff 

debug_pgsql_pool: debug_abb debug_abbs debug_pgsql_io 

debug_buildsys_intf: 

debug_terrat_vcs_provider2_github: debug_terrat_job_context_param debug_terrat_job_type debug_terrat_vcs_api_github debug_terrat_vcs_comment debug_terrat_vcs_provider2 

debug_terrat_api: debug_json_schema debug_openapi 

debug_showdown_js: 

test-debug: $(tests_debug)

test-debug_terrat_base_repo_config_v1: debug_oth debug_terrat_base_repo_config_v1 debug_terrat_repo_config 

test-debug_terrat_repo_config: debug_oth debug_terrat_repo_config 

test-debug_terrat_github_webhooks: debug_oth debug_terrat_github_webhooks 

test-debug_abb_time: debug_abb_time debug_oth 

test-debug_githubc2: debug_githubc2 debug_oth 

test-debug_abb_flow: debug_abb_flow debug_abb_scheduler_select debug_oth_abb 

test-debug_yaml_of_json: debug_oth debug_yaml_of_json 

test-debug_abb_future_combinators: debug_abb_fut debug_abb_future_combinators debug_abb_intf debug_oth 

test-debug_abb_fut: debug_abb_fut debug_abb_intf debug_oth 

test-debug_minijinja: debug_minijinja debug_oth 

test-debug_str_template: debug_oth debug_sln debug_str_template 

test-debug_jwt: debug_jwt debug_oth 

test-debug_buildsys: debug_abb_bounded_suspendable_executor debug_abb_fut debug_buildsys debug_oth debug_oth_abb 

test-debug_otls: debug_oth debug_otls 

test-debug_terrat_sql_of_tag_query: debug_oth debug_terrat_sql_of_tag_query debug_terrat_tag_query_ast 

test-debug_abb_channel_queue_fut: debug_abb_channel debug_abb_channel_queue debug_abb_fut debug_oth 

test-debug_abb_io: debug_abb_io debug_abb_scheduler_select debug_oth_abb 

test-debug_revops_ordering: debug_revops 

test-debug_oth: debug_oth 

test-debug_lua_pattern: debug_lua_pattern debug_oth 

test-debug_abb_bounded_suspendable_executor: debug_abb_bounded_suspendable_executor debug_abb_fut debug_abb_intf debug_oth 

test-debug_terrat: debug_oth debug_terrat 

test-debug_json_of_yaml: debug_json_of_yaml debug_oth 

test-debug_abb_thread_pool: debug_abb_thread_pool debug_oth 

test-debug_kqueue: debug_kqueue debug_oth 

test-debug_abb_scheduler_luv: debug_abb_intf debug_abb_scheduler_luv debug_abb_test 

test-debug_uritmpl: debug_oth debug_uritmpl 

test-debug_gitlabc: debug_gitlabc debug_oth 

test-debug_ttm_secrets: debug_oth debug_ttm_secrets 

test-debug_pgsql_codec: debug_oth debug_pgsql_codec 

test-debug_revops_undo: debug_revops 

test-debug_simple_diff: debug_oth debug_simple_diff 

test-debug_abb_scheduler_select: debug_abb_fut debug_abb_intf debug_abb_scheduler_select debug_abb_test 

test-debug_furi: debug_furi debug_oth 

test-debug_git_config: debug_git_config debug_oth 

test-debug_abb_scheduler_kqueue: debug_abb_intf debug_abb_scheduler_kqueue debug_abb_test 

test-debug_jsonu: debug_jsonu debug_oth 

test-debug_hcl_ast: debug_hcl_ast debug_oth 

test-debug_pgsql_io: debug_oth debug_pgsql_io 

test-debug_snabela: debug_oth debug_snabela 

test-debug_abb_cache: debug_abb_cache debug_abb_scheduler_select debug_oth_abb 

test-debug_abb_keyed_concurrent_executor: debug_abb_fut debug_abb_intf debug_abb_keyed_concurrent_executor debug_oth 

test-debug_terrat_vcs_comment: debug_oth debug_oth_abb debug_terrat_vcs_comment 

test-debug_revops_temp_file: debug_revops 

test-debug_jsonschema_check: debug_jsonschema_check debug_oth 

test-debug_abb_service_local: debug_abb_channel debug_abb_fut debug_abb_service_local debug_oth 

test-debug_cohttp_abb: debug_abb_scheduler_select debug_cohttp_abb debug_oth debug_oth_abb 

profile: $(projects_profile)

profile_terrat_ui_js_cache: 

profile_terrat_session: profile_brtl profile_brtl_mw_session profile_terrat_storage profile_terrat_user 

profile_kqueue_bindings_gen: profile_kqueue_bindings 

profile_terrat_tag_query_lexer: profile_terrat_tag_query_parser 

profile_abb_fut_js: profile_abb_fut 

profile_terrat_vcs_service: profile_brtl profile_terrat_config profile_terrat_storage profile_terrat_user profile_terrat_vcs_api profile_terrat_vcs_event_evaluator2 profile_terrat_vcs_provider2 

profile_terrat_vcs_service_nyi: 

profile_hcl_lexer: profile_hcl_parser 

profile_lua_pattern: 

profile_abb_js_xmlhttprequest: profile_abb_fut_js 

profile_terrat_access_token_caps: profile_json_schema profile_openapi 

profile_terrat_job_type: profile_json_schema 

profile_terrat_vcs_event_evaluator: profile_abb_flow profile_ouuid profile_prmths profile_sln profile_str_template profile_terrat_base_repo_config_v1 profile_terrat_comment profile_terrat_storage profile_terrat_user profile_terrat_vcs_provider2 

profile_terrat_user: profile_abb profile_jwt profile_pgsql_io profile_terrat_access_token_caps profile_terrat_storage profile_terrat_user_caps 

profile_ttm_kv: profile_abb profile_abbs profile_kv_store_intf profile_terrat_access_token_caps profile_terrat_user_caps profile_ttm_client 

profile_terrat_vcs_service_github: profile_brtl_permissions profile_minijinja profile_pgsql_io profile_pgsql_pagination profile_pgsql_pool profile_terrat_api profile_terrat_code_idx profile_terrat_files profile_terrat_github profile_terrat_github_webhooks profile_terrat_github_webhooks_decoder profile_terrat_metrics profile_terrat_plan_diff profile_terrat_scope profile_terrat_session profile_terrat_sql_of_tag_query profile_terrat_task profile_terrat_telemetry profile_terrat_user profile_terrat_vcs_api_github profile_terrat_vcs_event_evaluator profile_terrat_vcs_event_evaluator2 profile_terrat_vcs_github_comment profile_terrat_vcs_kv_store profile_terrat_vcs_provider2 profile_terrat_vcs_provider2_github profile_terrat_vcs_service profile_terrat_vcs_stacks 

profile_ttm: profile_abb profile_static_meta_pkg profile_ttm_kv profile_ttm_secrets 

profile_cohttp_abb_curl: profile_abb_intf profile_abb_io profile_abb_scheduler_select profile_cohttp_abb profile_otls 

profile_terrat_ee: profile_terrat_cli profile_terrat_vcs_service_github_ee profile_terrat_vcs_service_gitlab_ee 

profile_terrat_github: profile_abb profile_abbs profile_githubc2 profile_githubc2_abb profile_jwt profile_openapi profile_prmths profile_terrat_config 

profile_abb_bounded_suspendable_executor: profile_abb_intf profile_abb_service_local profile_abb_time 

profile_abb_curl_easy: profile_abb_intf 

profile_oth_abb: profile_abb_future_combinators profile_abb_intf profile_oth 

profile_terrat_ui_js_service_vcs: profile_abb_js profile_brtl_js2 profile_terrat_api profile_terrat_tier 

profile_terrat_code_indexer: profile_opentofu_mods profile_sln 

profile_jwk: 

profile_terrat_tier: 

profile_terrat: profile_abb profile_abb_cache profile_abb_curl profile_abb_flow profile_abb_happy_eyeballs profile_abb_keyed_concurrent_executor profile_abb_process profile_abbs profile_abbs_tls profile_brtl profile_brtl_ep profile_brtl_mw_log profile_brtl_mw_session profile_brtl_pagination profile_brtl_permissions profile_brtl_static profile_data_mig profile_git_config profile_githubc2 profile_githubc2_abb profile_jsonu profile_jwt profile_lua_pattern profile_ouuid profile_pgsql_pool profile_prmths profile_terrat_api profile_terrat_base_repo_config_v1 profile_terrat_change profile_terrat_change_match3 profile_terrat_code_idx profile_terrat_comment profile_terrat_commit_check profile_terrat_config profile_terrat_data profile_terrat_dirspace profile_terrat_files profile_terrat_metrics profile_terrat_migrations_ex profile_terrat_plan_diff profile_terrat_pull_request profile_terrat_repo_config profile_terrat_session profile_terrat_storage profile_terrat_tag_query profile_terrat_tag_query_ast profile_terrat_tag_query_lexer profile_terrat_tag_query_parser profile_terrat_tag_set profile_terrat_telemetry profile_terrat_user profile_terrat_vcs_service profile_terrat_work_manifest3 

profile_json_of_yaml: profile_json_of_yaml-rs 

profile_abb_thread_pool: 

profile_localforage: profile_abb_fut_js 

profile_terrat_ui_files: profile_terrat_ui_css profile_terrat_ui_js profile_terrat_ui_site 

profile_terrat_change_match3: profile_sln profile_terrat_base_repo_config_v1 profile_terrat_change profile_terrat_dirspace profile_terrat_tag_query 

profile_kqueue: profile_kqueue_bindings profile_kqueue_bindings_gen 

profile_terrat_files_gitlab: 

profile_abb_scheduler_luv: profile_abb_domain_pool profile_abb_fut profile_abb_intf 

profile_ttm_client: profile_abb profile_openapic_abb profile_terrat_api 

profile_uritmpl: 

profile_abb_intf: 

profile_terrat_vcs_event_evaluator2: profile_abb profile_abb_bounded_suspendable_executor profile_abbs profile_buildsys profile_ouuid profile_prmths profile_terrat_base_repo_config_v1 profile_terrat_comment profile_terrat_kv_store profile_terrat_storage profile_terrat_vcs_event_evaluator profile_terrat_vcs_event_evaluator2_targets profile_terrat_vcs_provider2 

profile_gitlabc: profile_json_schema profile_openapi 

profile_ttm_secrets: 

profile_kv_store_intf: 

profile_abb_tcp_server: profile_abb_channel profile_abb_channel_queue profile_abb_intf 

profile_pgsql_codec: 

profile_terrat_vcs_github_comment: profile_abb_future_combinators profile_minijinja profile_pgsql_io profile_pgsql_pagination profile_pgsql_pool profile_terrat_comment profile_terrat_files profile_terrat_github profile_terrat_plan_diff profile_terrat_scope profile_terrat_vcs_api_github profile_terrat_vcs_comment profile_terrat_vcs_github_comment_templates profile_terrat_vcs_provider2 profile_terrat_work_manifest3 

profile_terrat_task: profile_abb profile_abbs profile_pgsql_io profile_terrat_storage 

profile_terrat_ui_js_service_github: profile_abb_js profile_abb_js_fetch profile_brtl_js2 profile_tabler_icons profile_terrat_api profile_terrat_ui_js_service 

profile_terrat_migrations_ex: profile_pgsql_io profile_pgsql_pool profile_terrat_config profile_terrat_storage 

profile_terrat_vcs_service_github_oss: profile_terrat_vcs_api_github profile_terrat_vcs_provider2 profile_terrat_vcs_service profile_terrat_vcs_service_github 

profile_simple_diff: 

profile_abb_bounded_executor: profile_abb_intf profile_abb_service_local 

profile_abb_scheduler_select: profile_abb_fut profile_abb_intf profile_abb_thread_pool 

profile_terrat_vcs_provider2_nyi: profile_pgsql_io profile_terrat_vcs_api_nyi profile_terrat_vcs_provider2 

profile_dns_cli: profile_abb profile_abb_dns profile_abbs 

profile_json_schema: profile_sln profile_uritmpl 

profile_terrat_access_control2: profile_abb profile_abbs profile_terrat_base_repo_config_v1 profile_terrat_change profile_terrat_change_match3 profile_terrat_config 

profile_furi: 

profile_brtl_mw_log: profile_abb_intf profile_brtl 

profile_git_config: profile_sln 

profile_abb_scheduler_kqueue: profile_abb_domain_pool profile_abb_fut profile_abb_intf profile_kqueue 

profile_abb_channel: profile_abb_future_combinators profile_abb_intf 

profile_jsonu: profile_json_of_yaml profile_yaml_of_json 

profile_terrat_code_idx: profile_terrat_api 

profile_brtl_pagination: 

profile_snabela_cli: profile_snabela 

profile_hcl_ast: profile_hcl_lexer profile_hcl_parser profile_hcl_parser_value 

profile_lua_pattern_sed: profile_lua_pattern 

profile_abb: profile_abb_intf profile_abb_scheduler_luv 

profile_terrat_tag_query: profile_terrat_dirspace profile_terrat_tag_query_ast profile_terrat_tag_set 

profile_pgsql_io: profile_abb profile_abb_intf profile_abbs profile_abbs_tls profile_ouuid profile_pgsql_codec 

profile_abb_curl_cli: profile_abb_curl profile_abb_scheduler_luv 

profile_kqueue_bindings: 

profile_terrat_pull_request: 

profile_terrat_telemetry: profile_abb profile_abb_curl profile_abbs profile_terrat_config profile_terrat_work_manifest3 

profile_openapi: profile_json_schema 

profile_abb_curl_easy_cli: profile_abb_curl_easy profile_abb_scheduler_luv 

profile_terrat_work_manifest3: profile_terrat_base_repo_config_v1 profile_terrat_change profile_terrat_tag_query 

profile_terrat_ui_css: profile_tailwindcss profile_terrat_ui_js profile_terrat_ui_site 

profile_openapi_conv: profile_json_schema_conv profile_sln 

profile_snabela: profile_sln 

profile_opentofu_mods: profile_hcl_ast 

profile_json_of_yaml-rs: 

profile_abb_cache: profile_abb profile_abb_future_combinators profile_abb_intf profile_abb_io 

profile_githubc2_cli: profile_abb profile_abbs profile_githubc2 profile_githubc2_abb profile_otls 

profile_abb_dns: profile_abb_future_combinators profile_abb_intf profile_abb_io 

profile_abb_test: profile_abb_future_combinators profile_abb_intf profile_oth profile_oth_abb 

profile_service_worker: profile_abb_fut_js profile_abb_js 

profile_abb_keyed_concurrent_executor: profile_abb_future_combinators profile_abb_intf profile_abb_service_local 

profile_terrat_vcs_api_github: profile_githubc2 profile_githubc2_abb profile_prmths profile_terrat_github profile_terrat_metrics profile_terrat_pull_request profile_terrat_vcs_api 

profile_abb_tls: profile_abb_future_combinators profile_abb_intf profile_abb_io profile_otls 

profile_terrat_vcs_comment: profile_abbs profile_terrat_data profile_terrat_dirspace 

profile_abb_scheduler_nyi: profile_abb_fut profile_abb_intf 

profile_jsonschema_check: profile_jsonschema-rs 

profile_abb_js_fetch: profile_abb_fut_js 

profile_brtl_mw_session: profile_abb_intf profile_brtl 

profile_ouuid: 

profile_terrat_ui_sw: profile_abb_fut_js profile_brtl_js profile_service_worker profile_terrat_ui_js_cache 

profile_terrat_oss: profile_terrat_cli profile_terrat_vcs_service_github_oss profile_terrat_vcs_service_gitlab_oss 

profile_abb_service_local: profile_abb_channel profile_abb_channel_queue 

profile_json_schema_hooks_cli: profile_json_schema_conv 

profile_abb_curl: profile_abb_channel profile_abb_future_combinators profile_abb_intf profile_abb_service_local profile_sln 

profile_terrat_cli: profile_terrat profile_terrat_github 

profile_terrat_commit_check: 

profile_brtl_permissions: profile_abbs profile_brtl profile_brtl_ep 

profile_static_meta_pkg: 

profile_terrat_vcs_provider2: profile_abb profile_jsonu profile_pgsql_io profile_str_template profile_terrat_access_control2 profile_terrat_api profile_terrat_base_repo_config_v1 profile_terrat_change profile_terrat_commit_check profile_terrat_config profile_terrat_gate profile_terrat_job_context profile_terrat_pull_request profile_terrat_tier profile_terrat_vcs_api profile_terrat_vcs_stacks profile_terrat_work_manifest3 

profile_cohttp_abb: profile_abb_channel profile_abb_channel_queue profile_abb_future_combinators profile_abb_happy_eyeballs profile_abb_intf profile_abb_io profile_abb_tls profile_oth profile_oth_abb 

profile_abb_domain_pool: 

profile_terrat_vcs_api_nyi: profile_terrat_change profile_terrat_pull_request 

profile_terrat_tag_set: profile_sln 

profile_terrat_vcs_provider2_gitlab: profile_terrat_job_context_param profile_terrat_job_type profile_terrat_vcs_api_gitlab profile_terrat_vcs_comment profile_terrat_vcs_provider2 

profile_terrat_github_webhooks_decoder: profile_json_schema profile_terrat_github_webhooks 

profile_terrat_tag_query_parser_value: 

profile_opentofu_mods_cli: profile_opentofu_mods 

profile_brtl: profile_abb_intf profile_abbs profile_cohttp_abb profile_ouuid profile_snabela 

profile_terrat_files: 

profile_terrat_base_repo_config_v1: profile_jsonschema_check profile_lua_pattern profile_sln profile_terrat_data profile_terrat_repo_config profile_terrat_tag_query 

profile_terrat_ui_js_service: profile_abb_fut_js profile_abb_js profile_brtl_js2 profile_hljs profile_tabler_icons profile_terrat_api profile_terrat_dirspace profile_terrat_plan_diff profile_terrat_ui_js_service_vcs 

profile_revops: 

profile_terrat_config: 

profile_openapi_cli: profile_openapi_conv 

profile_jsonschema-rs: 

profile_brtl_static: profile_abbs profile_brtl 

profile_lua_pattern_cli: profile_lua_pattern 

profile_terrat_job_context_param: profile_json_schema 

profile_brtl_js: profile_abb_js profile_furi profile_ouuid 

profile_terrat_storage: profile_pgsql_pool profile_prmths profile_terrat_config 

profile_brtl_js2: profile_abb_js profile_furi 

profile_terrat_ui_site: profile_terrat_ui_js 

profile_hcl_parser: profile_hcl_parser_value 

profile_abb_js: profile_abb_fut_js profile_abb_future_combinators 

profile_terrat_data: profile_sln profile_terrat_dirspace 

profile_terrat_repo_config: profile_json_schema 

profile_hcl_ast_cli: profile_hcl_ast 

profile_openapic_abb: profile_abb profile_abb_curl profile_abbs profile_json_schema profile_openapi 

profile_data_mig: profile_abbs 

profile_terrat_github_webhooks: profile_json_schema 

profile_pgsql_test_client: profile_abb profile_abbs profile_oth profile_oth_abb profile_pgsql_io 

profile_githubc2_abb: profile_abb profile_abb_curl profile_abbs profile_json_schema profile_openapi 

profile_otls_bindings: 

profile_terrat_vcs_gitlab_comment: profile_abb_future_combinators profile_minijinja profile_pgsql_io profile_pgsql_pagination profile_pgsql_pool profile_terrat_comment profile_terrat_files_gitlab profile_terrat_plan_diff profile_terrat_scope profile_terrat_vcs_api_gitlab profile_terrat_vcs_comment profile_terrat_vcs_gitlab_comment_templates profile_terrat_vcs_provider2 profile_terrat_work_manifest3 

profile_terrat_vcs_access_token: profile_abb profile_brtl profile_brtl_ep profile_terrat_api profile_terrat_session profile_terrat_user profile_terrat_vcs_provider2 

profile_prmths: profile_abb profile_abbs 

profile_gitlab_webhooks_decoder: profile_gitlab_webhooks 

profile_terrat_vcs_stacks: profile_brtl profile_brtl_ep profile_terrat_api profile_terrat_change_match3 profile_terrat_session profile_terrat_storage profile_terrat_user profile_terrat_vcs_api 

profile_abb_time: 

profile_terrat_vcs_service_gitlab: profile_brtl_permissions profile_gitlab_webhooks profile_gitlab_webhooks_decoder profile_minijinja profile_pgsql_pagination profile_terrat_code_idx profile_terrat_files_gitlab profile_terrat_metrics profile_terrat_plan_diff profile_terrat_session profile_terrat_sql_of_tag_query profile_terrat_telemetry profile_terrat_vcs_access_token profile_terrat_vcs_api_gitlab profile_terrat_vcs_event_evaluator profile_terrat_vcs_event_evaluator2 profile_terrat_vcs_gitlab_comment profile_terrat_vcs_kv_store profile_terrat_vcs_provider2 profile_terrat_vcs_provider2_gitlab profile_terrat_vcs_service profile_terrat_vcs_stacks 

profile_terrat_vcs_api_gitlab: profile_gitlabc profile_openapic_abb profile_prmths profile_terrat_files_gitlab profile_terrat_vcs_api 

profile_brtl_hello_world: profile_abb profile_brtl profile_brtl_mw_log 

profile_iris: 

profile_githubc2: profile_json_schema profile_openapi 

profile_tabler_icons: profile_brtl_js2 

profile_tailwindcss: 

profile_terrat_change: profile_terrat_base_repo_config_v1 profile_terrat_data profile_terrat_dirspace 

profile_tls_server: profile_otls 

profile_abbs_tls: profile_abb profile_abb_tls 

profile_abb_flow: profile_abb_future_combinators profile_abb_intf 

profile_abb_channel_queue: profile_abb_channel profile_abb_future_combinators profile_abb_intf 

profile_json_schema_conv: profile_sln 

profile_terrat_vcs_event_evaluator2_targets: profile_terrat_base_repo_config_v1 profile_terrat_change profile_terrat_comment profile_terrat_dirspace profile_terrat_vcs_provider2 

profile_pds_excise: 

profile_terrat_vcs_service_gitlab_ee: profile_terrat_vcs_access_token profile_terrat_vcs_provider2 profile_terrat_vcs_service profile_terrat_vcs_service_gitlab 

profile_gitlab_webhooks: profile_json_schema 

profile_yaml_of_json: profile_yaml_of_json-rs 

profile_terrat_plan_diff: profile_lua_pattern 

profile_minijinja-rs: 

profile_terrat_scope: profile_terrat_api profile_terrat_data profile_terrat_dirspace 

profile_yaml_of_json-rs: 

profile_terrat_metrics: profile_prmths 

profile_terrat_vcs_api: profile_abb profile_pgsql_io profile_terrat_change profile_terrat_commit_check profile_terrat_config profile_terrat_pull_request 

profile_abb_future_combinators: profile_abb_intf 

profile_otls_bindings_gen: profile_otls_bindings 

profile_jwk_fetch: profile_abb profile_abbs profile_cohttp_abb profile_jwk 

profile_terrat_tag_query_parser: profile_terrat_tag_query_parser_value 

profile_abb_process: profile_abb_future_combinators profile_abb_intf 

profile_terrat_vcs_gitlab_comment_templates: profile_brtl profile_terrat_files_gitlab profile_terrat_plan_diff 

profile_terrat_ui_js_service_gitlab: profile_abb_js profile_abb_js_fetch profile_brtl_js2 profile_tabler_icons profile_terrat_api profile_terrat_ui_js_service 

profile_abb_fut: profile_abb_intf 

profile_abbs: profile_abb profile_abb_cache profile_abb_channel profile_abb_channel_queue profile_abb_future_combinators profile_abb_happy_eyeballs profile_abb_io profile_abb_service_local profile_abb_service_serializer profile_abb_tcp_server profile_abb_time 

profile_abb_happy_eyeballs: profile_abb_future_combinators profile_abb_intf 

profile_minijinja: profile_minijinja-rs 

profile_terrat_vcs_service_gitlab_oss: profile_terrat_vcs_provider2 profile_terrat_vcs_service profile_terrat_vcs_service_gitlab 

profile_terrat_kv_store: profile_abb profile_kv_store_intf profile_pgsql_io profile_terrat_user 

profile_str_template: profile_lua_pattern 

profile_terrat_ui_js: profile_abb_fut_js profile_abb_js profile_abb_js_fetch profile_brtl_js2 profile_hljs profile_tabler_icons profile_terrat_api profile_terrat_data profile_terrat_dirspace profile_terrat_plan_diff profile_terrat_ui_js_service profile_terrat_ui_js_service_github profile_terrat_ui_js_service_gitlab 

profile_terrat_vcs_service_github_ee: profile_sln profile_terrat_vcs_access_token profile_terrat_vcs_provider2 profile_terrat_vcs_service profile_terrat_vcs_service_github 

profile_terrat_comment: profile_terrat_tag_query 

profile_hljs: profile_brtl_js2 

profile_tls_client: profile_otls 

profile_terrat_gate: profile_terrat_api profile_terrat_base_repo_config_v1 

profile_abb_service_serializer: profile_abb_channel profile_abb_service_local 

profile_jwt: profile_sln 

profile_buildsys: profile_buildsys_intf 

profile_otls: profile_otls_bindings profile_otls_bindings_gen 

profile_sln: 

profile_terrat_sql_of_tag_query: profile_terrat_tag_query_parser_value 

profile_terrat_tag_query_ast: profile_terrat_tag_query_lexer profile_terrat_tag_query_parser profile_terrat_tag_query_parser_value 

profile_abb_io: profile_abb_future_combinators profile_abb_intf 

profile_markdown_it: 

profile_terrat_dirspace: 

profile_brtl_ep: profile_abbs profile_brtl 

profile_terrat_job_context: profile_terrat_api profile_terrat_tag_query 

profile_brtl_js_nav_bar: profile_abb_js profile_brtl_js 

profile_hcl_parser_value: 

profile_terrat_user_caps: profile_terrat_access_token_caps 

profile_oth: profile_revops 

profile_terrat_vcs_kv_store: profile_brtl profile_brtl_ep profile_terrat_kv_store profile_terrat_session profile_terrat_storage profile_terrat_user profile_terrat_vcs_provider2 

profile_pgsql_pagination: profile_abb profile_abbs profile_pgsql_io 

profile_terrat_vcs_github_comment_templates: profile_brtl profile_terrat_files profile_terrat_plan_diff 

profile_pgsql_pool: profile_abb profile_abbs profile_pgsql_io 

profile_buildsys_intf: 

profile_terrat_vcs_provider2_github: profile_terrat_job_context_param profile_terrat_job_type profile_terrat_vcs_api_github profile_terrat_vcs_comment profile_terrat_vcs_provider2 

profile_terrat_api: profile_json_schema profile_openapi 

profile_showdown_js: 

test-profile: $(tests_profile)

test-profile_terrat_base_repo_config_v1: profile_oth profile_terrat_base_repo_config_v1 profile_terrat_repo_config 

test-profile_terrat_repo_config: profile_oth profile_terrat_repo_config 

test-profile_terrat_github_webhooks: profile_oth profile_terrat_github_webhooks 

test-profile_abb_time: profile_abb_time profile_oth 

test-profile_githubc2: profile_githubc2 profile_oth 

test-profile_abb_flow: profile_abb_flow profile_abb_scheduler_select profile_oth_abb 

test-profile_yaml_of_json: profile_oth profile_yaml_of_json 

test-profile_abb_future_combinators: profile_abb_fut profile_abb_future_combinators profile_abb_intf profile_oth 

test-profile_abb_fut: profile_abb_fut profile_abb_intf profile_oth 

test-profile_minijinja: profile_minijinja profile_oth 

test-profile_str_template: profile_oth profile_sln profile_str_template 

test-profile_jwt: profile_jwt profile_oth 

test-profile_buildsys: profile_abb_bounded_suspendable_executor profile_abb_fut profile_buildsys profile_oth profile_oth_abb 

test-profile_otls: profile_oth profile_otls 

test-profile_terrat_sql_of_tag_query: profile_oth profile_terrat_sql_of_tag_query profile_terrat_tag_query_ast 

test-profile_abb_channel_queue_fut: profile_abb_channel profile_abb_channel_queue profile_abb_fut profile_oth 

test-profile_abb_io: profile_abb_io profile_abb_scheduler_select profile_oth_abb 

test-profile_revops_ordering: profile_revops 

test-profile_oth: profile_oth 

test-profile_lua_pattern: profile_lua_pattern profile_oth 

test-profile_abb_bounded_suspendable_executor: profile_abb_bounded_suspendable_executor profile_abb_fut profile_abb_intf profile_oth 

test-profile_terrat: profile_oth profile_terrat 

test-profile_json_of_yaml: profile_json_of_yaml profile_oth 

test-profile_abb_thread_pool: profile_abb_thread_pool profile_oth 

test-profile_kqueue: profile_kqueue profile_oth 

test-profile_abb_scheduler_luv: profile_abb_intf profile_abb_scheduler_luv profile_abb_test 

test-profile_uritmpl: profile_oth profile_uritmpl 

test-profile_gitlabc: profile_gitlabc profile_oth 

test-profile_ttm_secrets: profile_oth profile_ttm_secrets 

test-profile_pgsql_codec: profile_oth profile_pgsql_codec 

test-profile_revops_undo: profile_revops 

test-profile_simple_diff: profile_oth profile_simple_diff 

test-profile_abb_scheduler_select: profile_abb_fut profile_abb_intf profile_abb_scheduler_select profile_abb_test 

test-profile_furi: profile_furi profile_oth 

test-profile_git_config: profile_git_config profile_oth 

test-profile_abb_scheduler_kqueue: profile_abb_intf profile_abb_scheduler_kqueue profile_abb_test 

test-profile_jsonu: profile_jsonu profile_oth 

test-profile_hcl_ast: profile_hcl_ast profile_oth 

test-profile_pgsql_io: profile_oth profile_pgsql_io 

test-profile_snabela: profile_oth profile_snabela 

test-profile_abb_cache: profile_abb_cache profile_abb_scheduler_select profile_oth_abb 

test-profile_abb_keyed_concurrent_executor: profile_abb_fut profile_abb_intf profile_abb_keyed_concurrent_executor profile_oth 

test-profile_terrat_vcs_comment: profile_oth profile_oth_abb profile_terrat_vcs_comment 

test-profile_revops_temp_file: profile_revops 

test-profile_jsonschema_check: profile_jsonschema_check profile_oth 

test-profile_abb_service_local: profile_abb_channel profile_abb_fut profile_abb_service_local profile_oth 

test-profile_cohttp_abb: profile_abb_scheduler_select profile_cohttp_abb profile_oth profile_oth_abb 


test: test-release

install: $(projects_install)

docs: $(projects_docs)

remove: $(projects_remove)

clean:
	-rm -rf build/docs

clean: $(projects_clean_release) $(projects_clean_debug) $(projects_clean_profile) 

clean: $(tests_clean_release) $(tests_clean_debug) $(tests_clean_profile) 

$(projects_release):
	$(MAKE) \
	OCAMLPATH=$(shell pwd)/build/release:$(OCAMLPATH) \
	BUILD_DIR=$(shell pwd)/build/release/$(patsubst release_%,%,$@) \
	-C build/release/$(patsubst release_%,%,$@) release

$(projects_debug):
	$(MAKE) \
	OCAMLPATH=$(shell pwd)/build/debug:$(OCAMLPATH) \
	BUILD_DIR=$(shell pwd)/build/debug/$(patsubst debug_%,%,$@) \
	-C build/debug/$(patsubst debug_%,%,$@) debug

$(projects_profile):
	$(MAKE) \
	OCAMLPATH=$(shell pwd)/build/profile:$(OCAMLPATH) \
	BUILD_DIR=$(shell pwd)/build/profile/$(patsubst profile_%,%,$@) \
	-C build/profile/$(patsubst profile_%,%,$@) profile


$(projects_install): $(projects_release)
	$(MAKE) -C build/release/$(patsubst install_%,%,$@) install

$(tests_release):
	$(MAKE) \
	OCAMLPATH=$(shell pwd)/build/release:$(OCAMLPATH) \
	BUILD_DIR=$(shell pwd)/build/test-release/$(patsubst release_%,%,$@) \
	-C build/test-release/$(patsubst test-release_%,%,$@)

$(tests_debug):
	$(MAKE) \
	OCAMLPATH=$(shell pwd)/build/debug:$(OCAMLPATH) \
	BUILD_DIR=$(shell pwd)/build/test-debug/$(patsubst debug_%,%,$@) \
	-C build/test-debug/$(patsubst test-debug_%,%,$@)

$(tests_profile):
	$(MAKE) \
	OCAMLPATH=$(shell pwd)/build/profile:$(OCAMLPATH) \
	BUILD_DIR=$(shell pwd)/build/test-profile/$(patsubst profile_%,%,$@) \
	-C build/test-profile/$(patsubst test-profile_%,%,$@)


$(projects_docs): $(projects_release)
	mkdir -p $(shell pwd)/build/docs/$(patsubst docs_%,%,$@)
	$(MAKE) \
	OCAMLPATH=$(shell pwd)/build/release:$(OCAMLPATH) \
	BUILD_DIR=$(shell pwd)/build/docs/$(patsubst docs_%,%,$@) \
	-C build/release/$(patsubst docs_%,%,$@) docs

$(projects_remove):
	$(MAKE) -C build/release/$(patsubst remove_%,%,$@) remove

$(projects_clean_release):
	$(MAKE) \
	OCAMLPATH=$(shell pwd)/build/release:$(OCAMLPATH) \
	BUILD_DIR=$(shell pwd)/build/release/$(patsubst clean-release_%,%,$@) \
	-C build/release/$(patsubst clean-release_%,%,$@) clean

$(projects_clean_debug):
	$(MAKE) \
	OCAMLPATH=$(shell pwd)/build/debug:$(OCAMLPATH) \
	BUILD_DIR=$(shell pwd)/build/debug/$(patsubst clean-debug_%,%,$@) \
	-C build/debug/$(patsubst clean-debug_%,%,$@) clean

$(projects_clean_profile):
	$(MAKE) \
	OCAMLPATH=$(shell pwd)/build/profile:$(OCAMLPATH) \
	BUILD_DIR=$(shell pwd)/build/profile/$(patsubst clean-profile_%,%,$@) \
	-C build/profile/$(patsubst clean-profile_%,%,$@) clean


$(tests_clean_release):
	$(MAKE) \
	OCAMLPATH=$(shell pwd)/build/release:$(OCAMLPATH) \
	BUILD_DIR=$(shell pwd)/build/test-release/$(patsubst test-clean-release_%,%,$@) \
	-C build/test-release/$(patsubst test-clean-release_%,%,$@) test-clean

$(tests_clean_debug):
	$(MAKE) \
	OCAMLPATH=$(shell pwd)/build/debug:$(OCAMLPATH) \
	BUILD_DIR=$(shell pwd)/build/test-debug/$(patsubst test-clean-debug_%,%,$@) \
	-C build/test-debug/$(patsubst test-clean-debug_%,%,$@) test-clean

$(tests_clean_profile):
	$(MAKE) \
	OCAMLPATH=$(shell pwd)/build/profile:$(OCAMLPATH) \
	BUILD_DIR=$(shell pwd)/build/test-profile/$(patsubst test-clean-profile_%,%,$@) \
	-C build/test-profile/$(patsubst test-clean-profile_%,%,$@) test-clean

